name: Trigger Vercel Deployment on #deploy Commit

on:
  push:
    branches:
      - main

jobs:
  trigger-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # fetch full history to avoid invalid revision range error

      - name: Check commit messages for #deploy
        id: check_deploy
        run: |
          echo "Checking commits for #deploy keyword..."
          commits=$(git log --format=%B ${{ github.event.before }}..${{ github.sha }})
          echo "Commit messages in push:"
          echo "$commits"

          if echo "$commits" | grep -q "#deploy"; then
            echo "deploy=true" >> $GITHUB_OUTPUT
          else
            echo "deploy=false" >> $GITHUB_OUTPUT
          fi

      - name: Trigger Vercel Deployment
        if: steps.check_deploy.outputs.deploy == 'true'
        run: |
          curl -X POST ${{ secrets.VERCEL_DEPLOY_HOOK_URL }}
